---
- hosts: all
  become: yes
  gather_facts: False

  tasks:
    - name: Install packages
      become: yes
      apt: name=git state=present

    - name: Install packages
      become: yes
      apt: name=nmon state=present
