---

- name: "Install tmux"
  apt:
    name: tmux
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags:
    - tmux

- name: Configure tmux
  template:
    src: tmux.conf.j2
    dest: ~/.tmux.conf
    owner: "{{ user | default(ansible_user) }}"
    group: "{{ansible_user}}"
    mode: 0644
  tags:
    - tmux
