---

- name: Ensure crt folders exists
  file:
    path: "{{ cfssl_ssl_ca_dir }}"
    state: directory
    recurse: yes

- name: Check if ca private key exists
  stat:
    path: "{{ cfssl_ssl_ca_dir }}/ca-key.pem"
  register: ca_key_result

- block:
  - name: Create ca config file
    template:
      src: ca-config.json.j2
      dest: "{{ cfssl_ssl_ca_dir }}/ca-config.json"

  - name: Create csr config file
    template:
      src: csr.json.j2
      dest: "{{ cfssl_ssl_ca_dir }}/ca-csr.json"

  - name: Generate CA
    shell: "cfssl gencert -initca ca-csr.json | cfssljson -bare ca"
    args:
      chdir: "{{ cfssl_ssl_ca_dir }}"
    register: generate_ca_output

  - name: Output generate CA
    debug:
      msg: "{{ generate_ca_output.stderr }}"

  when: not ca_key_result.stat.exists |bool