---
# tasks file for vagrant installation 

- name: "Installing vagrant {{ vagrant_version }}"
  import_role:
    name: gantsign.visual-studio-code
  vars:
    visual_studio_code_extensions:
      - Go

