---
# tasks file for ansible-role-gnome

- name: "Task to choose install method for devel package {{ devel_package_name }}"
  include_tasks: "{{ install_devel_package }}"
  with_first_found:
    - files:
      - install_{{ devel_package_name }}.yml
      - install_default.yml
  loop_control:
    loop_var: install_devel_package

