---

- name: Workstation deployment
  hosts: all
  become: yes
  gather_facts: no
  vars:
    message: "OC-qa-LC-ms-travelclick-api"
    version: 1.10.3-0ubuntu0.16.04.3
  tasks:
    #- template: 
    #    src: dns.j2
    #    dest: dns

    - debug:
        msg: "{{ version | regex_replace('^([0-9]+.[0-9]+).*','\\1')}}"

    # - debug:
    # - demsg: "The IPv4 address for example.com. is {{ lookup('dig', 'budgetplaces.com.', '@1.0.0.1') }}"
