---

- name: Common tasks
  become: yes
  hosts: all
  tasks:
  - name: include ansible-role-kubernetes
    import_role:
      name: ansible-role-kubernetes

- name: kube-control-plane
  become: yes
  hosts: kube-control-plane
  tasks:
  - name: Kubernetes control plane
    import_role: 
      name: ansible-role-kubernetes
      tasks_from: kube-control-plane

- name: kube-worker
  become: yes
  hosts: kube-worker
  tasks:
  - name: Kubernetes worker 
    import_role: 
      name: ansible-role-kubernetes
      tasks_from: kube-worker
