name             'continuous_delivery'
maintainer       'Aleix Penella'
maintainer_email 'aleix.penella@gmail.com'
license          'All rights reserved'
description      'Installs and configures a continuous delivery environment'
long_description 'Installs and configures a continuous delivery environment'
version          '0.1.0'

depends 'docker', '~> 2.0'
depends 'jenkins', '~> 5.0.4'
