# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.berkshelf.enabled = true
	config.omnibus.chef_version = '12.20.3'

	$SERVER_IP = "10.0.0.5"	

	config.vm.define 'cd' do |env|
		env.vm.hostname = 'cd'
		env.vm.box = 'ubuntu/xenial64'
		#env.vm.box = 'centos/7'
		env.vm.network 'private_network', ip: "#{$SERVER_IP}"

		env.vm.provider 'virtualbox' do |vb|
			vb.name = 'continuousdelivery'
			vb.memory = 4096
			vb.cpus = 2
		end

		env.vm.provision "chef_solo" do |chef|
			#chef.log_level = :debug
			chef.add_recipe "continuous_delivery"

			chef.json = {
				:continuous_delivery => {
					:deploy => {
						:portainer => false,
						:registry_ui => false
					}
				},
				:jenkins => {
					:deploy => {
						'jenkins-data' => { 'clear': false },
						'jenkins-master' => { 'clear': false }
					}
				},
				:gitlab => {
					:deploy => {
						'clear': false
					},
					:config => {
						:external_url => "http://#{$SERVER_IP}"	
					}
				},
				:registry => {
					:deploy => {
						:clear => false
					},
					:config => {
						:host => "#{$SERVER_IP}",
						:port => '5000'
					}
				},
				:registry_ui => {
					:deploy => {
						:clear => false
					}
				},
				:portainer => {
					:deploy => {
						:clear => false
					},
					:config => {
						:port => '9000'
					}
				},
				:elk => {
					:deploy => {
						:clear => false
					}
				}
			}
  		end

  	end
end