---

- name: kubeadm achieve version
  command: kubeadm version -o short
  register: kubeadm_version

- name: kubeadm version
  debug:
    var: kubeadm_version

- name: kubeadm get configuration
  command: kubeadm config view
  register: kubeadm_config
  ignore_errors: yes

- name: Initialize kubernetes cluster
  command: |
    kubeadm init --token={{ kube_token }} \
    --apiserver-advertise-address={{ hostvars[inventory_hostname].ansible_host }} \
    --pod-network-cidr={{ kube_pod_network_cird }}
  register: kubeadm_init
  when: kubeadm_config.rc != 0

- name: Output kubeadm init
  debug:
    msg: "{{ kubeadm_init.stdout_lines }}"
  when: kubeadm_config.rc != 0

- name: Create kube folder
  become_user: "{{ ansible_user }}"
  file:
    path: $HOME/.kube
    state: directory
  register: kube_conf

- name: "Copy admin configuration to {{ ansible_user }}"
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ kube_conf.path }}/config"
    remote_src: yes 
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Include calico
  include_tasks: calico.yml
