---

- name: kubeadm worker join command
  command: "{{ kube_worker_join_commad }}"
  register: kubeadm_worker_join_command

- name: kubeadm kubeadm_worker_join_command
  debug:
    var: kubeadm_worker_join_command
