---
# tasks file for ansible-role-kubernetes

- name: Update system packages
  apt:
    update_cache: yes
    cache_valid_time: 86400

# - name: Upgrade system packages to lastest version
#   apt:
#     upgrade: dist

- name: Generate hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add kubernetes signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg 
    state: present

- name: Add kubernetes repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main 
    state: present

- name: Install Docker
  import_role:
    name: geerlingguy.docker

- name: Install common packages to install kubernetes
  apt:
    name: "{{ kube_common_packages }}"
    state: present
    autoclean: yes
    autoremove: yes
    update_cache: yes

- name: Enable docker
  service:
    name: docker
    state: started
    enabled: yes

# - name: Kubernetes control plane
#   include_role: 
#     name: ansible-role-kubernetes
#     tasks_from: kube-control-plane
#   when: inventory_hostname in groups['kube-control-plane']

# - name: Kubernetes worker 
#   include_role: 
#     name: ansible-role-kubernetes
#     tasks_from: kube-worker
#   when: inventory_hostname in groups['kube-worker']
