require 'yaml'

nodes_def = YAML.load_file('nodes.yml')

# This guide is optimized for Vagrant 1.7 and above.
# Although versions 1.6.x should behave very similarly, it is recommended
# to upgrade instead of disabling the requirement below.
Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  nodes_def.each do |node|
    config.vm.define node['name'] do |n|
      # node definition
      n.vm.hostname = node['name']
      n.vm.box = node['box']

      #puts node['vm']['name'] || node['name']

      # provider definition
      if node['vm'].is_a?(Hash)
        n.vm.provider 'virtualbox' do |vb|
          vb.name = node['vm']['name'] if node['vm'].key?('name')
          vb.memory = node['vm']['memory'] if node['vm'].key?('memory')
          vb.cpus = node['vm']['cpus'] if node['vm'].key?('cpus')
        end

	# synced folders (only basic synced)
        if node['vm'].key?('synced_folders') && !node['vm']['synced_folders'].nil?
          node['vm']['synced_folders'].each do |sf|
            if File.directory?(sf['src'])
              config.vm.synced_folder "#{sf['src']}", "#{sf['dest']}"
            end
          end
        end
      end

      # provision
      if node['ansible'].is_a?(Hash)
        n.vm.provision 'ansible' do |ansible|
          ansible.playbook = node['ansible']['playbook_path']
          ansible.verbose = node['ansible']['verbose'] if node['ansible'].key?('verbose')
          ansible.tags = node['ansible']['tags'] if node['ansible'].key?('tags')
          ansible.extra_vars = node['ansible']['extra_vars'] if node['ansible'].key?('extra_vars')
        end
      end
    end
  end
end
